<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="GORDITA" name="PositiveTest" tests="1" failures="1" timestamp="3 May 2020 05:19:00 GMT" time="44.18" errors="0">
  <testcase name="logInTest" time="44.126" classname="com.seleniumadvanced.github.PositiveTests">
    <failure type="java.lang.AssertionError" message="expected [http://the-internet.herokuapp.com/secure] but found [http://the-internet.herokuapp.com/login]">
      <![CDATA[java.lang.AssertionError: expected [http://the-internet.herokuapp.com/secure] but found [http://the-internet.herokuapp.com/login]
	at com.seleniumadvanced.github.PositiveTests.logInTest(PositiveTests.java:46)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:283)
	at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:120)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- logInTest -->
</testsuite> <!-- PositiveTest -->
